[tool.black]
line-length=79
target-version = [
  "py35",
  "py36",
  "py37",
  "py38",
  "py39",
  "py310",
#   "py311",  # black 21.12b0 doesn't
#   "py312",  # support these targets
]
exclude = '''
/(
    \.eggs/
  | \.git/
  | \.tox/
  | \.venv/
  | _build/
  | build/
  | dist/
  | venv/
)
'''
[tool.pyright]
executionEnvironments=[
  {"root" = "xpay"},
  {"root" = "tests"}
]
include=["xpay", "tests/test_generated_examples.py"]
exclude=["build", "**/__pycache__"]
reportMissingTypeArgument=true
reportUnnecessaryCast=true
reportUnnecessaryComparison=true
reportUnnecessaryContains=true
reportUnnecessaryIsInstance=true
